services:
  painel-qrbrasil:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: painel-qrbrasil
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=fvbsCq72kHnKWb1JpM5zgGS0wMN
    networks:
      - painel-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Proxy reverso com Nginx (opcional)
  nginx:
    image: nginx:alpine
    container_name: painel-qrbrasil-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - painel-qrbrasil
    networks:
      - painel-network

networks:
  painel-network:
    driver: bridge

volumes:
  ssl: 